### ISSUE TITLE
Skate 5: ESNext Build Issue

### ISSUE THREAD

**Issue by alexlafroscia** [skatejs/skatejs#1209]
Using the `esnext` build from Skate 5 (through `generator-skatejs`) I'm getting the following error:

```bash
$ "/path/to/my/project/node_modules/.bin/webpack" --config webpack/development.js
Hash: f490a8e240a99fe4f8f0
Version: webpack 3.4.0
Time: 1973ms
                          Asset    Size  Chunks                    Chunk Names
nest-coverage-checker.bundle.js  419 kB       0  [emitted]  [big]  main
   [5] ./src/index.js 99 bytes {0} [built]
   [7] ./src/nest-coverage-checker/component.js 5.54 kB {0} [built]
  [15] ./src/util/style.js 1.13 kB {0} [built]
  [16] ./src/nest-coverage-checker/styles.scss 263 bytes {0} [built]
  [17] ./src/util/check-zip-code.js 498 bytes {0} [built]
    + 13 hidden modules

ERROR in ./node_modules/skatejs/esnext/with-component.js
Module not found: Error: Can't resolve '../../node_modules/preact/dist/preact.esm.js' in '/path/to/my/project/node_modules/skatejs/esnext'
 @ ./node_modules/skatejs/esnext/with-component.js 10:17-72
 @ ./node_modules/skatejs/esnext/index.js
 @ ./src/nest-coverage-checker/component.js
 @ ./src/index.js
error Command failed with exit code 2.
```

I checked it out, and it seems like the source of the `with-components.js` older uses a relative path to the `preact` dependency, a path that is not correct when both `skatejs` and `preact` are dependencies of some project.

**Comment by alexlafroscia** [comment]
Actually, you're not doing anything weird here...

https://github.com/skatejs/skatejs/blob/f6af0b85df57d6bd5402b08da6adfa0fce939765/src/with-component.js#L3

I wonder where it's getting that incorrect relative path from?

**Comment by alexlafroscia** [comment]
Ahh, here is it:

https://github.com/skatejs/skatejs/blob/f6af0b85df57d6bd5402b08da6adfa0fce939765/config/esnext.babel.js#L4

Any insight into the reason for this change @matthewp?

**Comment by alexlafroscia** [comment]
Yup, that fixed it.

**Comment by matthewp** [comment]
Ah, ok. I know what's going on then. I'm afk for a few days but I'll fix it when I get back.

**Comment by alexlafroscia** [comment]
Awesome 👍  thanks!

**Comment by treshugart** [comment]
@matthewp is this fixed now (probably just needs releasing)?

**Comment by matthewp** [comment]
I was going to do a release and test it out, just haven't had a chance to do so yet.

**Comment by treshugart** [comment]
I just did an `alpha.15`.

**Comment by alexlafroscia** [comment]
I'm still having the issue in `alpha.15`. The path to the Preact file has one `../` too few.

**Comment by treshugart** [comment]
Oh right, I conflated it with another issue.

**Comment by matthewp** [comment]
Ah, ok, I see now.  This is the problem: https://github.com/matthewp/babel-plugin-modules-web-compat/issues/5

I'll fix that after work today and then try an alpha.16.

**Comment by matthewp** [comment]
Is there any process to the release? Bump the version manually and then run the release script?

**Comment by matthewp** [comment]
Well, that's what I just did... testing.

**Comment by matthewp** [comment]
Finally!

![screen shot 2017-08-17 at 5 47 10 pm](https://user-images.githubusercontent.com/361671/29435131-c656436a-8373-11e7-9f06-258f09f0abcc.png)

**Comment by alexlafroscia** [comment]
Whoop! Tested myself, can confirm it's fixed. Thanks @matthewp!
